### ISSUE TITLE
the project is private?

### ISSUE THREAD

**Issue by robotrono** [solkin/trashpad#12]
I want to install this project  in my server, is possible?

**Comment by solkin** [comment]
This project is public, so, you can install it on your own server.

**Comment by robotrono** [comment]
Thanks for the response, im trying to install in localhost but this have a script to install?

**Comment by solkin** [comment]
You only needs to copy `service/data/config_default.ini` to `service/data/config.ini` and make changes in `[database]` section to configure your DB.

Then run `index.php?init=true&admin=secret_key`

**Comment by robotrono** [comment]
Thanks!, i dont know why dont work with xampp (windows) in localhost, but works fine in my hosting.  

https://i.imgur.com/ZrS0MJN.png

How can delete threads? via admin

**Comment by solkin** [comment]
For now, to open admin features, you just need to add parameter `?admin=secret_key` to the URL. 
After that you can downvote threads, remove threads/comments and show extended browser info of user, posted thread/comment.

**Comment by robotrono** [comment]
Thanks!
Well im trying now to show thread "pinned" i see the functions for a query in utils.php I add this:

```
function get_pinned_thread($link, $include_reply) {
  $sql = "SELECT * FROM threads WHERE pin = '1' ORDER BY id DESC";
  $result = mysqli_query($link, $sql) or die('{"status": "failed", "reason": ' . json_encode(mysqli_error($link)) . '}');

  return list_threads($link, $result, $include_reply);
}
```
now how can show this query in index, im so confused, btw sorry for my bad english

**Comment by solkin** [comment]
As I understand:
`index.php:18`
`$threads_list = get_pinned_thread($link, true);`
